import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:firebase_auth/firebase_auth.dart';

import 'firebase_options.dart'; // generated by running: flutterfire configure
import 'pages/table_order_page.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();

  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );

  // Sign the customer in anonymously so Firestore security rules have a
  // uid to check against, without ever showing a login screen to guests.
  if (FirebaseAuth.instance.currentUser == null) {
    await FirebaseAuth.instance.signInAnonymously();
  }

  runApp(const PlatesAndPoursApp());
}

class PlatesAndPoursApp extends StatelessWidget {
  const PlatesAndPoursApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Plates & Pours',
      debugShowCheckedModeBanner: false,
      theme: ThemeData(
        useMaterial3: true,
        colorSchemeSeed: const Color(0xFF2E7D32), // garden-green accent
      ),
      home: const TableOrderPage(),
    );
  }
}
