// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2zlLW7OUTYEi-gkzONmz9wYIPgqlH5XA',
    appId: '1:789517333866:web:5fb492c23ec1e23521e113',
    messagingSenderId: '789517333866',
    projectId: 'platesandpours',
    authDomain: 'platesandpours.firebaseapp.com',
    storageBucket: 'platesandpours.firebasestorage.app',
    measurementId: 'G-3ECZ4ZV67P',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB1SRmwjlfqGwc_yOjq1_uYVmv7aAn7rQA',
    appId: '1:789517333866:ios:c14a6867b538c15d21e113',
    messagingSenderId: '789517333866',
    projectId: 'platesandpours',
    storageBucket: 'platesandpours.firebasestorage.app',
    iosBundleId: 'com.example.platesAndPoursWeb',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1SRmwjlfqGwc_yOjq1_uYVmv7aAn7rQA',
    appId: '1:789517333866:ios:c14a6867b538c15d21e113',
    messagingSenderId: '789517333866',
    projectId: 'platesandpours',
    storageBucket: 'platesandpours.firebasestorage.app',
    iosBundleId: 'com.example.platesAndPoursWeb',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1SRmwjlfqGwc_yOjq1_uYVmv7aAn7rQA',
    appId: '1:789517333866:android:25d4bd833a27022321e113',
    messagingSenderId: '789517333866',
    projectId: 'platesandpours',
    storageBucket: 'platesandpours.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB1SRmwjlfqGwc_yOjq1_uYVmv7aAn7rQA',
    appId: '1:789517333866:web:5b91c74d04ca73f521e113',
    messagingSenderId: '789517333866',
    projectId: 'platesandpours',
    authDomain: 'platesandpours.firebaseapp.com',
    storageBucket: 'platesandpours.firebasestorage.app',
    measurementId: 'G-EEZ1H6TR9L',
  );
}
