import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';

import 'firebase_options.dart'; // generated by running: flutterfire configure
import 'pages/welcome_page.dart';
import 'theme/app_theme.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();

  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );

  runApp(const PlatesAndPoursApp());
}

class PlatesAndPoursApp extends StatelessWidget {
  const PlatesAndPoursApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Plates & Pours',
      debugShowCheckedModeBanner: false,
      theme: buildAppTheme(),
      // WelcomePage decides guest-vs-login, then hands off to the menu —
      // this is the "Has Account / Logged In?" branch from the flowchart.
      home: const WelcomePage(),
    );
  }
}
